apiVersion: v1
kind: ConfigMap
metadata:
  name: viba-image-nginx
  namespace: prod-annotation
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
      include /etc/nginx/mime.types;
      upstream flask_app { server 127.0.0.1:5001; }
      server {
        listen 80;
        # redirect /annot-image -> /annot-image/
        location = /annot-image { return 301 /annot-image/; }
        # Static under subpath /annot-image using alias
        location /annot-image/ {
          alias /usr/share/nginx/html/;
          index index.html;
          try_files $uri $uri/ /index.html;
        }
        # API direct
        location /api/ {
          proxy_pass http://flask_app;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          client_max_body_size 50M;
          proxy_read_timeout 300s;
          proxy_connect_timeout 75s;
        }
        # API under subpath /annot-image/api -> /api
        location /annot-image/api/ {
          rewrite ^/annot-image/api/(.*)$ /api/$1 break;
          proxy_pass http://flask_app;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          client_max_body_size 50M;
          proxy_read_timeout 300s;
          proxy_connect_timeout 75s;
        }
        location /health { proxy_pass http://flask_app; }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: viba-image-secrets
  namespace: prod-annotation
type: Opaque
stringData:
  DB_HOST: sceno-prod-db.cbsomsec2v5x.us-west-2.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: db_userx
  # IAM 认证模式下不需要密码
  # DB_PASSWORD: your_db_password
  S3_BUCKET_NAME: viba-internal # 根据环境修改
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viba-image
  namespace: prod-annotation
spec:
  replicas: 2
  selector:
    matchLabels: { app: viba-image }
  template:
    metadata:
      labels: { app: viba-image }
    spec:
      serviceAccountName: annot-backend-sa
      containers:
        - name: backend
          image: 686255979277.dkr.ecr.us-west-2.amazonaws.com/internal/annot-image-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              valueFrom: { secretKeyRef: { name: viba-image-secrets, key: DB_HOST } }
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: viba-image-secrets, key: DB_PORT } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: viba-image-secrets, key: DB_NAME } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: viba-image-secrets, key: DB_USER } }
            # IAM 认证时移除密码
            # - name: DB_PASSWORD
            #   valueFrom: { secretKeyRef: { name: viba-image-secrets, key: DB_PASSWORD } }
            - name: DB_AUTH_MODE
              value: "iam"
            - name: DB_SSLMODE
              value: "require"
            - name: AWS_REGION
              value: "us-west-2"
            - name: S3_BUCKET_NAME
              valueFrom: { secretKeyRef: { name: viba-image-secrets, key: S3_BUCKET_NAME } }
            - name: S3_PREFIX
              value: "viba-image-annotation/"
            - name: S3_REGION
              value: "us-west-2"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
        - name: nginx
          image: 686255979277.dkr.ecr.us-west-2.amazonaws.com/internal/annot-image-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /annot-image/
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /annot-image/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: nginx-conf
          configMap:
            name: viba-image-nginx
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: viba-image-svc
  namespace: prod-annotation
spec:
  selector: { app: viba-image }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP