
apiVersion: v1
kind: ConfigMap
metadata:
  name: viba-theme-nginx
  namespace: prod-annotation
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
      include /etc/nginx/mime.types;
      upstream flask_app { server 127.0.0.1:5001; }
      server {
        listen 80;
        # redirect /annot-theme -> /annot-theme/
        location = /annot-theme { return 301 /annot-theme/; }
        # Static under subpath /annot-theme using alias
        location /annot-theme/ {
          alias /usr/share/nginx/html/;
          index index.html;
          try_files $uri $uri/ /index.html;
        }
        # API direct
        location /api/ {
          proxy_pass http://flask_app;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          client_max_body_size 20M;
          proxy_read_timeout 300s;
          proxy_connect_timeout 75s;
        }
        # API under subpath /annot-theme/api -> /api
        location /annot-theme/api/ {
          rewrite ^/annot-theme/api/(.*)$ /api/$1 break;
          proxy_pass http://flask_app;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          client_max_body_size 20M;
          proxy_read_timeout 300s;
          proxy_connect_timeout 75s;
        }
        location /health { proxy_pass http://flask_app; }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: viba-theme-secrets
  namespace: prod-annotation
type: Opaque
stringData:
  DB_HOST: sceno-prod-db.cbsomsec2v5x.us-west-2.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: db_userx
  # 若 DB_AUTH_MODE=iam 则不需要密码
  # DB_PASSWORD: your_db_password
  S3_BUCKET_NAME: viba-internal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viba-theme
  namespace: prod-annotation
spec:
  replicas: 2
  selector:
    matchLabels: { app: viba-theme }
  template:
    metadata:
      labels: { app: viba-theme }
    spec:
      serviceAccountName: annot-backend-sa
      containers:
        - name: backend
          image: 686255979277.dkr.ecr.us-west-2.amazonaws.com/internal/annot-theme-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              valueFrom: { secretKeyRef: { name: viba-theme-secrets, key: DB_HOST } }
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: viba-theme-secrets, key: DB_PORT } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: viba-theme-secrets, key: DB_NAME } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: viba-theme-secrets, key: DB_USER } }
            # 切换为 IAM 认证时，移除 DB_PASSWORD 并设置 DB_AUTH_MODE=iam
            # - name: DB_PASSWORD
            #   valueFrom: { secretKeyRef: { name: viba-theme-secrets, key: DB_PASSWORD } }
            - name: DB_AUTH_MODE
              value: "iam"
            - name: DB_SSLMODE
              value: "require"
            - name: AWS_REGION
              value: "us-west-2"
            - name: S3_BUCKET_NAME
              valueFrom: { secretKeyRef: { name: viba-theme-secrets, key: S3_BUCKET_NAME } }
            - name: S3_PREFIX
              value: "internal-viba-theme-tool/"
        - name: nginx
          # 使用你的前端制品镜像，镜像内已包含构建产物和 nginx.conf
          image: 686255979277.dkr.ecr.us-west-2.amazonaws.com/internal/annot-theme-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: viba-theme-nginx
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: viba-theme-svc
  namespace: prod-annotation
spec:
  selector: { app: viba-theme }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP



